future: true

# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Shalitha's Tech blog
paginate:       5
baseurl:        "http://shalithasuranga.me/blog"
url:            "http://shalithasuranga.me/blog"
homeurl:        "http://shalithasuranga.me"
githubrepo:     "https://github.com/shalithasuranga/blog/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Shalitha Suranga
  url:          http://shalithasuranga.me/blog
  email:        shalithasuranga@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
gems:
  - jekyll-paginate
